### ISSUE TITLE
security issue in tensorflow

### ISSUE THREAD

**Issue by Wouter1** [INFLUENCEorg/aiagents#18]
On 03/06/2020 14:42, Aleksander Czechowski wrote:
> Github informed me that there is a security vulnerability in the dependencies.
> Could you please look into that?
> How should we change the required version of tensorflow,
> so there is no more vulnerability and the tests run correctly?

Date: | Thu, 21 May 2020 12:00:46 +0000
-- | --
GitHub <notifications@github.com>
INFLUENCEorg/influence-aware-memory               <noreply@github.com>
INFLUENCEorg/influence-aware-memory               <influence-aware-memory@noreply.github.com>
Security alert <security_alert@noreply.github.com>

czechows,

We found a vulnerable dependency in a repository you have security alert access to.

INFLUENCEorg/influence-aware-memory 

Known  high severity                                 security vulnerability detected in tensorflow                                   < 1.15.2 defined in requirements.txt. | Known  high severity                                 security vulnerability detected in tensorflow                                   < 1.15.2 defined in requirements.txt.
-- | --
Known  high severity                                 security vulnerability detected in tensorflow                                   < 1.15.2 defined in requirements.txt.

The readme.txt file is referred to as 
https://github.com/INFLUENCEorg/influence-aware-memory/blob/master/requirements.txt

**Comment by Wouter1** [comment]
Mailed Alex

This issue is reported on the project "influence-aware-memory".

How does this relate to aienvs and aiagents?

**Comment by Wouter1** [comment]
@czechows 

FYI, setup.py in aiagents does not depend on a specific version of tensorflow.
It also does not have a requirements.txt file as setup.py already specifies requirements.

I suppose that means aiagents uses the latest version  and then there would be no issue to be solved here.

**Comment by czechows** [comment]
Great!
